IBL tutorials
dandi/example-notebooks pull request #40
Opened 2023-09-05 10:48 UTC by oliche

Added some basic tutorials for use at Neurodatarehack 2023

2023-09-05 12:22 UTC, bendichter commented on .gitignore
> +000409/paper-brain-wide-map/
Was this supposed to be added here?

2023-09-05 12:22 UTC, bendichter requested changes
@oliche this is great! Would you mind adding a small README outlining the purpose of the different notebooks available?

2023-09-05 13:12 UTC, satra commented
@oliche - could you also please structure the additions in the way the README describes: `<dandiset>/<orgorlab>/...`

2023-09-05 16:11 UTC, satra commented
@oliche - @yarikoptic enabled codespell and there a few things that are being picked up that should be fixed. but there are others that are being misinterpreted. @yarikoptic - do you have any suggestions on best practice for people submitting notebooks. perhaps add that to the README of the repo.

2023-09-06 07:18 UTC, oliche commented
Yeah but most of the errors are related to other notebooks.
As for my notebooks, it's not really working as the brain region acronyms and the logs are not amenable to spell checks.


```
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1863: ot ==> to, of, or, not
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1863: nOO ==> no
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1863: Ot ==> To, Of, Or, Not
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1863: yuO ==> you
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: bu ==> by, be, but, bug, bun, bud, buy, bum
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: bu ==> by, be, but, bug, bun, bud, buy, bum
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: OLL ==> ALL, OLE, OLD, OLLY, OIL
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: fo ==> of, for, to, do, go
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: fOf ==> for
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: uE ==> use, due
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: SoM ==> some
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: fo ==> of, for, to, do, go
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: fwe ==> few
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: whe ==> when, we
Error: ./000409/IBL/03_analysis_Imbizo_2023.ipynb:1915: te ==> the, be, we, to
``

2023-09-06 10:20 UTC, bendichter approved these changes

2023-09-06 10:21 UTC, merged